from pydantic import BaseModel, Field
from typing import Optional, List

class AgentConfig(BaseModel):
    model_name: str = Field(..., description="The name of the LLM model to use.")
    temperature: Optional[float] = Field(0.7, description="Sampling temperature for the model.")
    max_tokens: Optional[int] = Field(150, description="Maximum number of tokens to generate.")

class AgentInput(BaseModel):
    prompt: str = Field(..., description="The input prompt for the AI agent.")
    context: Optional[str] = Field(None, description="Optional context to provide additional information.")

class AgentResponse(BaseModel):
    response: str = Field(..., description="The response generated by the AI agent.")
    tokens_used: int = Field(..., description="Number of tokens used in the response.")
    model: str = Field(..., description="The model used to generate the response.")