CREATE (:`Security` {id: 'Cmbs Security Msbam 2017-C34', type: 'Security'});
CREATE (:`Organization` {id: 'S&P', type: 'Organization'});
CREATE (:`Property` {id: '444 West Ocean Blvd, Long Beach', type: 'Property'});
CREATE (:`Organization` {id: 'Jpmorgan', type: 'Organization'});
CREATE (:`Organization` {id: 'Premier Business Centers', type: 'Organization'});
CREATE (:`Location` {id: 'Los Angeles, Ca', type: 'Location'});
CREATE (:`Property` {id: '888 East Ocean, Short Beach', type: 'Property'});
CREATE (:`Organization` {id: 'Wells Fargo', type: 'Organization'});
CREATE (:`Organization` {id: 'Premier Industry Centers', type: 'Organization'});
CREATE (:`Location` {id: 'San Francisco, Ca', type: 'Location'});
CREATE (:`Property` {id: '101 Market Street, Oakland', type: 'Property'});
CREATE (:`Organization` {id: 'Citibank', type: 'Organization'});
CREATE (:`Organization` {id: 'Bluewave Financial Group', type: 'Organization'});
CREATE (:`Organization` {id: 'Flexstart Co-Working', type: 'Organization'});
CREATE (:`Property` {id: '707 Mission Street, San Jose', type: 'Property'});
CREATE (:`Organization` {id: 'Bank Of America', type: 'Organization'});
CREATE (:`Organization` {id: 'Innovatex Labs', type: 'Organization'});
CREATE (:`Organization` {id: 'Bitcore Systems', type: 'Organization'});
CREATE (:`Property` {id: '3200 Wilshire Blvd, Koreatown, Los Angeles', type: 'Property'});
CREATE (:`Organization` {id: 'Morgan Stanley', type: 'Organization'});
CREATE (:`Organization` {id: 'K-Fashion World', type: 'Organization'});
CREATE (:`Organization` {id: 'Urban Fresh Foods', type: 'Organization'});
CREATE (:`Property` {id: '500 2Nd Avenue, Seattle', type: 'Property'});
CREATE (:`Organization` {id: 'Goldman Sachs', type: 'Organization'});
CREATE (:`Organization` {id: 'Pacific Northwest Freight Co.', type: 'Organization'});
MATCH (a {id: 'Cmbs Security Msbam 2017-C34'}), (b {id: 'S&P'}) CREATE (a)-[:`RATED_BY`]->(b);
MATCH (a {id: 'Cmbs Security Msbam 2017-C34'}), (b {id: '444 West Ocean Blvd, Long Beach'}) CREATE (a)-[:`SECURED_BY`]->(b);
MATCH (a {id: '444 West Ocean Blvd, Long Beach'}), (b {id: 'Jpmorgan'}) CREATE (a)-[:`ORIGINATED_BY`]->(b);
MATCH (a {id: '444 West Ocean Blvd, Long Beach'}), (b {id: 'Premier Business Centers'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '444 West Ocean Blvd, Long Beach'}), (b {id: 'Los Angeles, Ca'}) CREATE (a)-[:`LOCATED_IN`]->(b);
MATCH (a {id: 'Cmbs Security Msbam 2017-C34'}), (b {id: '888 East Ocean, Short Beach'}) CREATE (a)-[:`SECURED_BY`]->(b);
MATCH (a {id: '888 East Ocean, Short Beach'}), (b {id: 'Wells Fargo'}) CREATE (a)-[:`ORIGINATED_BY`]->(b);
MATCH (a {id: '888 East Ocean, Short Beach'}), (b {id: 'Premier Industry Centers'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '888 East Ocean, Short Beach'}), (b {id: 'San Francisco, Ca'}) CREATE (a)-[:`LOCATED_IN`]->(b);
MATCH (a {id: 'Cmbs Security Msbam 2017-C34'}), (b {id: '101 Market Street, Oakland'}) CREATE (a)-[:`SECURED_BY`]->(b);
MATCH (a {id: '101 Market Street, Oakland'}), (b {id: 'Citibank'}) CREATE (a)-[:`ORIGINATED_BY`]->(b);
MATCH (a {id: '101 Market Street, Oakland'}), (b {id: 'Bluewave Financial Group'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '101 Market Street, Oakland'}), (b {id: 'Flexstart Co-Working'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '101 Market Street, Oakland'}), (b {id: 'Oakland, Ca'}) CREATE (a)-[:`LOCATED_IN`]->(b);
MATCH (a {id: 'Cmbs Security Msbam 2017-C34'}), (b {id: '707 Mission Street, San Jose'}) CREATE (a)-[:`SECURED_BY`]->(b);
MATCH (a {id: '707 Mission Street, San Jose'}), (b {id: 'Bank Of America'}) CREATE (a)-[:`ORIGINATED_BY`]->(b);
MATCH (a {id: '707 Mission Street, San Jose'}), (b {id: 'Innovatex Labs'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '707 Mission Street, San Jose'}), (b {id: 'Bitcore Systems'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '707 Mission Street, San Jose'}), (b {id: 'San Jose, Ca'}) CREATE (a)-[:`LOCATED_IN`]->(b);
MATCH (a {id: 'Cmbs Security Msbam 2017-C34'}), (b {id: '3200 Wilshire Blvd, Koreatown, Los Angeles'}) CREATE (a)-[:`SECURED_BY`]->(b);
MATCH (a {id: '3200 Wilshire Blvd, Koreatown, Los Angeles'}), (b {id: 'Morgan Stanley'}) CREATE (a)-[:`ORIGINATED_BY`]->(b);
MATCH (a {id: '3200 Wilshire Blvd, Koreatown, Los Angeles'}), (b {id: 'K-Fashion World'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '3200 Wilshire Blvd, Koreatown, Los Angeles'}), (b {id: 'Urban Fresh Foods'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '3200 Wilshire Blvd, Koreatown, Los Angeles'}), (b {id: 'Los Angeles, Ca'}) CREATE (a)-[:`LOCATED_IN`]->(b);
MATCH (a {id: 'Cmbs Security Msbam 2017-C34'}), (b {id: '500 2Nd Avenue, Seattle'}) CREATE (a)-[:`SECURED_BY`]->(b);
MATCH (a {id: '500 2Nd Avenue, Seattle'}), (b {id: 'Goldman Sachs'}) CREATE (a)-[:`ORIGINATED_BY`]->(b);
MATCH (a {id: '500 2Nd Avenue, Seattle'}), (b {id: 'Pacific Northwest Freight Co.'}) CREATE (a)-[:`LEASED_TO`]->(b);
MATCH (a {id: '500 2Nd Avenue, Seattle'}), (b {id: 'Seattle, Wa'}) CREATE (a)-[:`LOCATED_IN`]->(b);
